<?php
	$data = array("html"=> '<div style="background-color:#ffffff; width:500px;">
		<div style=" padding:10px;">
			<p>Conteúdo a ser carregado com dados passados via json:<span style="color:#999999;"> '.$_POST['valor'].'</span></p>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tincidunt, metus non faucibus dignissim, ante neque pulvinar neque, eget tristique quam libero at enim. Nullam vel eros ut sem volutpat ultrices et sit amet sapien. Maecenas tincidunt posuere ligula sed efficitur. In pellentesque enim eget nunc bibendum, quis dignissim dui hendrerit. Ut id pharetra quam. Nunc a tincidunt nisi. Vestibulum in molestie metus, sed imperdiet ligula. Nunc suscipit tellus non ultrices convallis. Etiam pharetra fringilla arcu.Vestibulum eleifend sapien lacus, et sollicitudin eros dictum eu. Sed libero erat, dictum vel tellus vitae, gravida auctor ipsum. Vivamus lacus risus, semper quis dignissim id, vestibulum non nisl. Sed ipsum diam, viverra quis sagittis eu, rhoncus et nisi. Etiam eu tristique mauris, quis sodales nulla. Cras id posuere mauris. Nullam id sapien nec felis sollicitudin tincidunt. Donec tincidunt arcu neque, at tincidunt est accumsan non. Proin posuere massa id nisl posuere convallis. Integer vel sem placerat, ullamcorper lectus non, porta massa. Vestibulum vel leo velit. Aliquam eget vestibulum dui, pulvinar facilisis diam. Curabitur scelerisque, orci at aliquam feugiat, ligula orci pulvinar metus, ut porttitor orci ipsum quis leo.Nunc viverra, urna a finibus tempor, metus sapien pulvinar ligula, sed rutrum ante sapien eget urna. Aenean fringilla viverra neque, at semper eros sollicitudin at. Nunc consectetur efficitur sem, sed facilisis nulla pretium bibendum. Integer sed neque eget dolor rutrum rhoncus. Morbi consectetur nibh diam, in aliquet nisl elementum pharetra. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque auctor fermentum vehicula.Sed convallis porttitor magna nec blandit. Aliquam eget faucibus velit. Cras bibendum, lectus in iaculis dapibus, mauris metus laoreet sem, non vestibulum justo lacus eu felis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi vel tellus odio. Curabitur ultrices tortor semper purus interdum, id tincidunt erat viverra. Donec at augue dapibus, dapibus tellus non, pretium lectus. Morbi pharetra elementum malesuada. Nulla viverra, ipsum sed lobortis faucibus, nisl metus iaculis nisi, a fermentum risus justo eget odio. Duis et dui quis odio tincidunt accumsan a ac nisl. Maecenas vulputate id tortor et venenatis. Phasellus ac magna egestas, vestibulum orci sed, posuere nibh.Nulla imperdiet rutrum ligula. Suspendisse gravida justo vel massa lacinia gravida. Phasellus id nulla elementum tellus semper accumsan eget non urna. Cras luctus lorem non nisl porttitor dapibus eu ac eros. Nullam tempus risus a justo tempor fringilla. Proin turpis felis, tempor quis blandit nec, congue quis felis. Pellentesque id mattis metus. Mauris eleifend faucibus orci a gravida. Duis ut leo pellentesque, placerat ante eu, commodo ante.</p>
			<a id="bt-overlay" href="#" style="border:1px solid #000000; padding:10px; display:inline-block;">abrir novo overlay</a>
		</div>
	</div>');
	
	echo json_encode($data);
	//echo '<div style="background-color:#ffffff; width:500px; height:300px;"><p>Conteudo a ser carregado</p></div>';
	
?>